security:
  enable_authenticator_manager: true

  password_hashers:
    App\Entity\Member:
      algorithm: auto

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Member
        property: email

  firewalls:
    main:
      provider: app_user_provider
      custom_authenticators:
        - App\Security\LoginFormAuthenticator

      logout:
        path: app_logout
        target: home

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/home, roles: ROLE_USER }
