security:
  encoders:
    App\Entity\Member:
      algorithm: auto

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Member
        property: email

  firewalls:
    main:
      anonymous: true
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        username_parameter: email
        password_parameter: password
        default_target_path: home
        always_use_default_target_path: true
        csrf_token_generator: security.csrf.token_manager
      logout:
        path: app_logout
        target: home

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/home, roles: ROLE_USER }
