version: '3'

services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "9003:9003" # Xdebug için port
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: symfony_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
