<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240801111329 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add roles column to member table with default value';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql('ALTER TABLE member ADD roles JSON NOT NULL DEFAULT \'["ROLE_USER"]\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->addSql('ALTER TABLE member DROP roles');
    }
}
