index:
    path: /
    controller: App\Controller\DefaultController::index
admin_member:
    path: /admin/member
    controller: App\Controller\Admin\MemberController::index
    defaults:
        path: /adminbase.html.twig
member_delete:
    path: /admin/member/delete/{id}
    controller: App\Controller\Admin\MemberController::delete
member_create:
    path: /admin/member/create
    controller: App\Controller\Admin\MemberController::create
category_show:
    path: /category/{id}
    controller: App\Controller\Admin\CategoryController::show

