# config/services.yaml
parameters:
  images_directory: '%kernel.project_dir%/public/img'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Repository\UserRepository:
    tags: ['doctrine.repository_service']

  App\Controller\MemberController:
    autowire: true
    public: true
